apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: database-creds
  namespace: mylife
spec:
  encryptedData:
    mongodb-passwords: AgC7WGhPEW7/WZDtski76B0NMX22zC3ijKlGRBIBQQdcXdUkIwBti4YaPtTiMYSETgs8ZEjbVKVixJMgolH6AP6dTc/CjFuIVC+USg6IMPosKdC7FxiyRDAiZGj4bcT5HPiCVq3wtNsZ7gM8iYrbd15MgJwH4JvtBLkOxGgkUj5Qr1hvV7rYHmS1k4FxRVzD5Ud+UJ+NIi198T+03zVQ+hf9PbIB4bPXxaCTTBzDMn89S9HVd6hy7RiSpJfwVJGIrzLLaK4ZdPEbz9bnGvVWmz75Mc1EHxZ1us7BffkjhCWN90TPdVhcmJLMVKN6Nrevr5YwI3u+91BGvKBIoBKtUVH0VvHoDMir6IFIHY2RHWIpxNA1UQn5wR3bcIzG3pUS0xxbqEDTGlow7wpgqnv9Gmk8ZgejLC8Wg0c+mZCZNfeyIqjtdTwrl2cjHhm4XoLCEQ0bjsQbETX2xEzbL8vbdY8yqKRG1q6kaFRatH0CA9oBQxpb0KjdIYUaOZpoF5wsj/GgsF7riMrDaDhF3kdsw7EKNGm2CH1Jh3Gq66HLRVv4pQl78WM/5zcd+gENWOBI4lsET7DVwmCvWA6Y3fd0BmNgEpLLTmxA2W/oQBJGON3zLWrSzCotn8pikYc/5vyFuinmGmd2qlkvXPSuk2vJhbQJlxt7RHfsb608H0UnE0DKCG4qRzoetP2/1Np6Q6yV3wBIIqEbqOcGJsRnHTAezWy/Pm6KFqlbeLv+
    mongodb-root-password: AgBrb5+XC10g0z50lLdToTA6EdkWZ3eN0qPWM36IWDUHXvzUXQjehvKaHkvZCluXjOfXrYxO9Pa25WEE1kxrtiJC3t1a9XOimey/4ID7t2MzP1vGrIdcGIOn1nyFdcPUmmiOlDTW6r8nRTg+B/H2Ad3AwEk+3Q4oHlEwwrHr6Z83cGo2n2m3evzQU/CJhLu8Q/oIR1bG72153mHpGbAJOiz61YS3uk00YuJarDZtFdHdIcJxmYq200FIErwJ6PEJd1kQ0NE2Skq1SDtrhMc6SASFaMPoUVPJISsbNXk2jwEs4aplKbwiMBDpU2Be6Rvpdh6stdaSbGy39ZNsa2tKDczwFrE979M/c8LuMd8zy17xFGs1cto+hFRgF73dq1DztfYh2UPYD+9jwZISWan3Ij7JL9nRmYzNUhBawzewmd8k7djjET/GTcl533orha175c0RnEDTFORjIRzRHp5WPKHljg4fAOE3yeWm6GBrJigE0+r+hFl82a+I9jwHuVi3RqfC3yzRsDd99FbHtVQrCh1UD5s2m4inG3Z+JV2M3KLOPyQR3ORtBnv/iXHLY3mKHdkvytjVZ2ComfryjTsrcn5Yh8/fhiF270NahGUha0Yfj0KbqCkEMuQGE4EKxQtTsvuVENEwalgiFHZaNEcRlh15kKf3S+oNO5RmyiBqx/8YA1YtWKIj4HpUttjU+h5x5YU2dYg/iqKXojObnS7IUF9nNn8xm/f4Mw==
  template:
    metadata:
      namespace: mylife
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: database-creds
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mylife-telegram-details
  namespace: mylife
spec:
  encryptedData:
    TELEGRAM_CHAT_ID: AgC8txXWSkf+E7fibGvcMKME83ICKEYZ3tQZAqASH5Yr0USJ74+tX0Pg+EXNbUqImM9D+bzM0+XCI1QR8TpLOpkOrSqvUpPSxe6F1j26Q88aHjXxFTzNOtbIQvuu97wlzUDwGJzJrN7A1nfCGWgLNHO1Omx/7jdWprnQT10wwjnSACdVXzHwUC8S/LMlXOrYZOqkth2fHUZg44QRn4Ez9EuHfjcGzxq0FOC40MY8m1txhNAmQa7OYqmm6NkuRbS3N2uNwgNCjVQ5KJg3hplmNKtfAqo9w7UCY3H4w8hfDt64U8Xec00aPjQj7WgUw2RuAtmcAVv8f0yGX/wfO5upqRvlu8k4uBLcIAMY8Lj7TVC0/un2SoTAAMPZXzmCv8MqPFrjLkHmgmBU3OmEAokGb4ztPgRSb/bhN86qoWGD5FnEImmMo+o21J+hDG8PIz4zzv6eUIomGIIHKg3Ti4sp1EKBRmZiwlmZ8itrOSigzKI0F+jYFEVYkoGWIC8CsSnPEzOJb/oLa/cc2vRBZi92S4IlzBIIj5dcNGqCloA7/3E2EcyP72Nbn1rhlJRHAqdZJsjEGa1GKmAgYfRq9e+R68HFpDuEaL6MQY+F9osWG4rl9FSumblbVTRbuYALQiiLb/ecDI/IE3R+XHVbqnlTeogiA3FH3F9mV2jLCP1ha8ilxF/huozlecPYTiNQxuHIn+O+9NDRNXCNNUAL
    TELEGRAM_TOKEN: AgB7i5e44mqJOLCQmYsI4QvUL9BUD2JgDF9D/E1nFjKNjQlRTE8WVJKkWlXHaENoTHXbWHOJkbaSl4TUhcWZPLV+Cj8WpfEjK7XgH2XtfTEeeWWACRyJUUomDOzfYjgqbgbiOCCdD8ksSQarw3xZsRhgDX6krMcGr1b9aV39jvHT3jiGnOVsku4memeQju0U1mZRjvqi5Qt0SUdEPchpyd3nsOclJ9dhIZ+q9JTdirLWXepw9b5g4RaVEjkOJn155o20zmEG7IfI9Kpn40ZGkgde8troZHa3kiKnBvVTIS76DkXwjcs8zEJX/7YWu92wHDdVrrRut1T3XP9gKnw1yZ3rk6TAt4IGjwsVcU5gYqB9ckcvVjPloKU8/NCMgUgNtiW+iPGGTjs04mHOeEoXmSpL6iGT4DzjMu5kMQesAJQVEREbhPwI7GZ0eoKrJZnsHsYxP56ksR2/y2J62DCx+wZBu1Ag/clbhIWRjMAaZCMaZ468Xv++aRLbCoZCmFYxF3kMVNuNDPfPhbXRPpR6/yYEm8X3VIBjNiWPM+w25KLWHDV6o8NObsr/LhH8GAYQgrVlZdXYnxyk1VVrylKOADUua5gSxrOT+BZbDfiXJeH1VLR1Jr1bU+kN9W1CJaii1LTYJT/yqArP8bBqGKO3SRUaXn5cvIr2UfkzHPG2mQA0LJeaSOW+UZX9Jz/s7alUkQPGeXrF3HTDSX8nAYD8BQMOD5+yw5Pw13iIr9KxaluYFWJK+myt6scGfSFlK2xc
  template:
    metadata:
      creationTimestamp: null
      name: mylife-telegram-details
      namespace: mylife
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dockerauth
  namespace: mylife
spec:
  encryptedData:
    .dockerconfigjson: AgA/5pWoaAOce0hOb10ZMUsgGjaCAYmLFVDfdKToeqbBEU3UaooetW3GydT3S3B8S8biwhtJlh5xYK5Y27IMNi6HDfCU6853RBm/8mdbxzILXQ9RyPRpQZ+eXJbgS49YeMw06/VSb4cRyTIEwH8hZ70Iglp3gDkby9m3k6C0EZco0+9S08BQuN6QRVG5QwpJXzE4/7JLPYtF32AVFwbTXYuTBVpIj7rHxdE7RpNwmvmxM/l5m3+HfTWGVsloCaTx1bPwxQTfFqsQikwJqCO/ahFDM+vwhNx7SAtIq8NxgFaG43AtNsMkyYpxBXcXvi1oMoqhOONppBQF8bkmKk51C8UtABAfC8VUGzcTddbe39Ccdhi/UDwzV80mJzKUouBv848Z+CIjwHaFups8HPKlJYu8UgemsbVBhwRfwSK8+nD76xXX2Rx23KzTL+hGHKptthbnU3MOZHSomfkvWxy28c56wFDW2qvmp7nowmWC2t+oWTYS7Zmoh7Uu/O1krVv5ur+SkeRL4I1K0QxTTPIkd15mgaKWUbX3N1D1RS//sMveoNIbsVXIpoxgFa9dm5hX/PDE/b9BDW4XPoyRiSNGu8/h7MnJo8tzIPs0alW50O7ezBHL2Cskq35lomObKdBpRZGkktitAp7yNrkQi3Y3r8cl3ZikqyIIOuIMgiRdRDrqEddnL+RSTH6v7fFG5+yDPDgAW+ymBEpKQzfjOy0/8hPoYU0oQeAbWEXB2HklEaFBhFnd/wQJWivGPs9tobB9U36uI3iQtuPkvgVR+52ULWnj8UnL4WUCghYx0IS3PC4c+TbFTsujyMf7GPG6FSemIwaKZzyHbkyI+FIx9IWx51qpSqTlxUJqZfe0B3HacXW71Ij9tUIEGhUay4bqZuK0lvW+DXdijx/cVLn09n8DFgtDEffyyVPMWWwJzEAUfdoG55TMgTubnwZDUG4i45U59zsFlZZdcw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: dockerauth
      namespace: mylife
    type: kubernetes.io/dockerconfigjson
