name: Create Telegram Bot Docker image

on:
  push:
    branches: 
      - main
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "assets/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/imdevinc/mylife-telegram:latest
            ghcr.io/imdevinc/mylife-telegram:${{ steps.vars.outputs.sha_short }}
          push: true
